import type { Voucher, Place, TripPlan } from './types';

export const VOUCHERS: Voucher[] = [
  {
    id: 'munhwa-nuri',
    name: '문화누리카드',
    color: '#16a34a',
    maxAmount: 150000,
    benefitType: 'balance',
    description: '기초생활수급자·차상위계층을 위한 국내 문화·관광·체육 지원 카드',
  },
  {
    id: 'disabled-welfare-card',
    name: '장애인등록증(복지카드)',
    color: '#7c3aed',
    maxAmount: 0,
    benefitType: 'discount',
    description: '국·공립 관광시설 무료 및 교통·공공체육시설 요금 감면 자격',
  },
  {
    id: 'worker-vacation',
    name: '근로자 휴가지원사업',
    color: '#2563eb',
    maxAmount: 100000,
    benefitType: 'program',
    description: '참여 근로자의 국내여행 상품 구매를 돕는 정부·기업 공동 적립 제도',
  },
];

export const REGIONS = [
  '서울', '부산', '인천', '대구', '광주', '대전', '울산', '세종',
  '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주',
];

export const TOURISM_TYPES = [
  { id: 'nature', name: '자연', emoji: '🌿' },
  { id: 'culture', name: '문화', emoji: '🏛️' },
  { id: 'history', name: '역사', emoji: '🏯' },
  { id: 'experience', name: '체험', emoji: '🎨' },
  { id: 'performance', name: '공연·축제', emoji: '🎭' },
  { id: 'rest', name: '휴식', emoji: '☕' },
  { id: 'sports', name: '레포츠', emoji: '🏃' },
  { id: 'shopping', name: '쇼핑', emoji: '🛍️' },
];

export const TRANSPORTATION_OPTIONS = [
  { id: 'public', name: '대중교통 이용', emoji: '🚌' },
  { id: 'car', name: '자가용 이용', emoji: '🚗' },
  { id: 'min-walk', name: '도보 이동 최소화', emoji: '🦽' },
  { id: 'parking', name: '주차 필요', emoji: '🅿️' },
  { id: 'nearby', name: '가까운 장소 우선', emoji: '📍' },
];

export const ACCESSIBILITY_CONDITIONS = [
  { id: 'wheelchair', name: '휠체어 접근 가능', emoji: '♿' },
  { id: 'disabled-toilet', name: '장애인 화장실', emoji: '🚻' },
  { id: 'disabled-parking', name: '장애인 주차구역', emoji: '🅿️' },
  { id: 'elevator', name: '엘리베이터', emoji: '🛗' },
  { id: 'baby', name: '유아 동반 편의시설', emoji: '👶' },
  { id: 'senior', name: '고령자 이용 편의', emoji: '👴' },
  { id: 'rest-area', name: '휴식 공간', emoji: '💺' },
];

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    name: '경복궁',
    type: '역사',
    types: ['history', 'culture'],
    region: '서울',
    city: '종로구',
    address: '서울특별시 종로구 사직로 161',
    phone: '02-3700-3900',
    image: 'https://images.unsplash.com/photo-1599033769063-fcd3ef816810?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.7,
    reviewCount: 12453,
    voucherStatus: 'available',
    voucherStatusDetail: '문화누리카드로 입장료 전액 이용 가능합니다.',
    entryFee: 3000,
    selfPay: 0,
    accessibility: {
      wheelchair: true,
      disabledToilet: true,
      disabledParking: true,
      elevator: false,
      babyFacility: true,
      seniorFriendly: true,
      restArea: true,
    },
    operatingHours: '09:00 ~ 18:00 (11~1월 17:00까지)',
    closedDays: '매주 화요일',
    description: '조선왕조의 법궁으로, 북악산 기슭에 자리한 역사문화 명소입니다. 1395년 창건된 후 임진왜란으로 소실되었다가 고종 때 중건되었습니다.',
    highlights: ['수문장 교대식 (10:00, 14:00)', '한복 착용 시 무료 입장', '광화문·근정전 관람'],
    lastUpdated: '2026-06-15',
    distance: 2.1,
    transportOptions: ['지하철 3호선 경복궁역 5번 출구'],
    recommendReason: '문화누리카드 전액 사용 가능, 휠체어 접근 가능, 장애인 편의시설 완비',
  },
  {
    id: '2',
    name: '국립중앙박물관',
    type: '문화',
    types: ['culture', 'history'],
    region: '서울',
    city: '용산구',
    address: '서울특별시 용산구 서빙고로 137',
    phone: '02-2077-9000',
    image: 'https://images.unsplash.com/photo-1529883406927-e996c9ae3353?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.8,
    reviewCount: 8921,
    voucherStatus: 'available',
    voucherStatusDetail: '상설전시관 무료, 특별전시 문화누리카드 사용 가능합니다.',
    entryFee: 0,
    selfPay: 0,
    accessibility: {
      wheelchair: true,
      disabledToilet: true,
      disabledParking: true,
      elevator: true,
      babyFacility: true,
      seniorFriendly: true,
      restArea: true,
    },
    operatingHours: '10:00 ~ 18:00 (수·토 21:00까지)',
    closedDays: '매주 월요일, 1월 1일',
    description: '우리나라 최대 규모의 박물관으로 선사시대부터 근대까지의 유물 43만여 점을 소장하고 있습니다.',
    highlights: ['금동미륵보살반가사유상', '청자 컬렉션', '세계문화관', '어린이박물관'],
    lastUpdated: '2026-07-01',
    distance: 4.3,
    transportOptions: ['지하철 4호선·경의중앙선 이촌역 2번 출구'],
    recommendReason: '무료 입장, 완벽한 배리어프리 시설, 모든 편의시설 완비',
  },
  {
    id: '3',
    name: '한국민속촌',
    type: '체험',
    types: ['experience', 'culture', 'history'],
    region: '경기',
    city: '용인시',
    address: '경기도 용인시 기흥구 민속촌로 90',
    phone: '031-288-0000',
    image: 'https://images.unsplash.com/photo-1703825864792-5880081beaaf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.5,
    reviewCount: 6234,
    voucherStatus: 'conditional',
    voucherStatusDetail: '온라인 예매 시에만 문화누리카드 사용 가능합니다. 현장 결제는 불가합니다.',
    entryFee: 25000,
    selfPay: 5000,
    accessibility: {
      wheelchair: true,
      disabledToilet: true,
      disabledParking: true,
      elevator: false,
      babyFacility: true,
      seniorFriendly: false,
      restArea: true,
    },
    operatingHours: '09:30 ~ 18:00',
    closedDays: '연중무휴',
    description: '조선시대 생활문화를 체험할 수 있는 야외 민속 박물관으로, 270여 채의 전통 가옥이 복원되어 있습니다.',
    highlights: ['전통공예 체험', '줄타기·마상무예 공연', '전통 음식 체험'],
    lastUpdated: '2026-05-20',
    distance: 38.5,
    transportOptions: ['수원역 → 37·10-5번 버스 (60분)', '에버랜드 방면 셔틀버스'],
    recommendReason: '전통문화 체험 최적, 온라인 예매 시 문화누리카드 사용 가능',
  },
  {
    id: '4',
    name: '천지연 폭포',
    type: '자연',
    types: ['nature'],
    region: '제주',
    city: '서귀포시',
    address: '제주특별자치도 서귀포시 천지동 667-7',
    phone: '064-760-6304',
    image: 'https://images.unsplash.com/photo-1628411848698-e3b3249a272a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.6,
    reviewCount: 9876,
    voucherStatus: 'check',
    voucherStatusDetail: '관광정보 최종 확인일(2025.11)과 가맹점 정보가 일치하지 않아 방문 전 전화 확인을 권장합니다.',
    entryFee: 2000,
    selfPay: 2000,
    accessibility: {
      wheelchair: false,
      disabledToilet: true,
      disabledParking: true,
      elevator: false,
      babyFacility: true,
      seniorFriendly: false,
      restArea: true,
    },
    operatingHours: '09:00 ~ 22:00',
    closedDays: '연중무휴',
    description: '서귀포시 중심부에 위치한 높이 22m의 자연 폭포로, 천연기념물 문어발·뱀장어 등이 서식합니다.',
    highlights: ['야간 조명 폭포 (일몰 후)', '열대어 서식지', '600m 산책로'],
    lastUpdated: '2025-11-10',
    distance: 0,
    transportOptions: ['서귀포 시내버스 510·520번', '렌터카 이용'],
    recommendReason: '제주 대표 자연 명소, 야간 조명 폭포 추천 (바우처 이용 가능 여부 사전 확인 필요)',
  },
  {
    id: '5',
    name: '부산 해운대해수욕장',
    type: '자연',
    types: ['nature', 'rest', 'sports'],
    region: '부산',
    city: '해운대구',
    address: '부산광역시 해운대구 해운대해변로 264',
    phone: '051-749-7601',
    image: 'https://images.unsplash.com/photo-1556966346-0215efedf4d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.4,
    reviewCount: 15342,
    voucherStatus: 'unavailable',
    voucherStatusDetail: '해수욕장 자체는 무료이나, 주변 상업시설에 현재 확인된 문화누리카드 가맹점이 없습니다.',
    entryFee: 0,
    selfPay: 0,
    accessibility: {
      wheelchair: true,
      disabledToilet: true,
      disabledParking: true,
      elevator: false,
      babyFacility: true,
      seniorFriendly: true,
      restArea: true,
    },
    operatingHours: '상시 개방',
    closedDays: '없음',
    description: '부산을 대표하는 해수욕장으로 약 1.8km의 백사장이 펼쳐지며, 마린시티와 달맞이고개를 배경으로 한 아름다운 경관을 자랑합니다.',
    highlights: ['백사장 산책 (1.8km)', '일출·일몰 포토스팟', '아쿠아리움·에스플라나드'],
    lastUpdated: '2026-07-10',
    distance: 0,
    transportOptions: ['지하철 2호선 해운대역 3·5번 출구'],
    recommendReason: '무료 입장, 완벽한 접근성, 여름 최적 여행지 (바우처 사용처 별도 확인 필요)',
  },
  {
    id: '6',
    name: '전주 한옥마을',
    type: '문화',
    types: ['culture', 'history', 'experience', 'shopping'],
    region: '전북',
    city: '전주시',
    address: '전라북도 전주시 완산구 기린대로 99',
    phone: '063-282-1330',
    image: 'https://images.unsplash.com/photo-1535189043414-47a3c49a0bed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.6,
    reviewCount: 18923,
    voucherStatus: 'available',
    voucherStatusDetail: '한옥마을 내 다수 문화·체험 시설에서 문화누리카드를 사용할 수 있습니다.',
    entryFee: 0,
    selfPay: 0,
    accessibility: {
      wheelchair: true,
      disabledToilet: true,
      disabledParking: true,
      elevator: false,
      babyFacility: true,
      seniorFriendly: true,
      restArea: true,
    },
    operatingHours: '상시 (시설별 상이)',
    closedDays: '없음',
    description: '700여 채의 전통 한옥이 모여있는 국내 최대 규모의 한옥마을로, 조선시대 생활문화와 전통문화를 체험할 수 있습니다.',
    highlights: ['전통 한복 체험', '비빔밥 투어', '한지·공예 체험', '경기전 (이성계 어진 봉안)'],
    lastUpdated: '2026-06-28',
    distance: 0,
    transportOptions: ['KTX 전주역 → 79·119번 버스 (10분)'],
    recommendReason: '문화누리카드 사용처 다수, 평지 위주 이동 가능, 다양한 체험 프로그램',
  },
  {
    id: '7',
    name: '설악산 국립공원',
    type: '자연',
    types: ['nature', 'sports'],
    region: '강원',
    city: '속초시',
    address: '강원특별자치도 속초시 설악동 170',
    phone: '033-801-0900',
    image: 'https://images.unsplash.com/photo-1540998263728-032f59903a86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.8,
    reviewCount: 22341,
    voucherStatus: 'conditional',
    voucherStatusDetail: '입장료에 문화누리카드 사용 가능. 케이블카 이용권은 별도 현금 결제가 필요합니다.',
    entryFee: 3500,
    selfPay: 0,
    accessibility: {
      wheelchair: false,
      disabledToilet: true,
      disabledParking: true,
      elevator: false,
      babyFacility: false,
      seniorFriendly: false,
      restArea: true,
    },
    operatingHours: '05:00 ~ 19:00 (계절·구간별 상이)',
    closedDays: '연중무휴 (기상 악화 시 통제)',
    description: '대한민국 최고의 산악 경관을 자랑하는 국립공원으로, 가야동·천불동 계곡과 권금성 케이블카가 유명합니다.',
    highlights: ['권금성 케이블카 (별도 비용)', '울산바위 전망', '비선대 계곡'],
    lastUpdated: '2026-04-05',
    distance: 0,
    transportOptions: ['속초시외버스터미널 → 설악산행 시내버스 7-1번'],
    recommendReason: '국내 최고 자연경관, 입장권 문화누리카드 사용 가능 (케이블카 별도)',
  },
  {
    id: '8',
    name: '국립현대미술관 서울관',
    type: '문화',
    types: ['culture'],
    region: '서울',
    city: '종로구',
    address: '서울특별시 종로구 삼청로 30',
    phone: '02-3701-9500',
    image: 'https://images.unsplash.com/photo-1575391304128-f11964816ef6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
    rating: 4.5,
    reviewCount: 5678,
    voucherStatus: 'available',
    voucherStatusDetail: '상설전시 및 기획 특별전 모두 문화누리카드로 이용 가능합니다.',
    entryFee: 4000,
    selfPay: 0,
    accessibility: {
      wheelchair: true,
      disabledToilet: true,
      disabledParking: true,
      elevator: true,
      babyFacility: true,
      seniorFriendly: true,
      restArea: true,
    },
    operatingHours: '10:00 ~ 18:00 (금·토 21:00까지)',
    closedDays: '매주 월요일',
    description: '경복궁 옆에 위치한 현대미술 전문 미술관으로 국내외 현대미술 작품을 전시하며, 야외 조각공원도 무료로 관람할 수 있습니다.',
    highlights: ['야외 조각공원 (무료)', '기획 특별전', '아트샵·카페'],
    lastUpdated: '2026-07-05',
    distance: 2.8,
    transportOptions: ['지하철 3호선 경복궁역·안국역'],
    recommendReason: '완벽한 배리어프리 시설, 문화누리카드 이용 가능, 경복궁과 함께 관람 추천',
  },
];

export const SAMPLE_SAVED_TRIPS: TripPlan[] = [
  {
    id: 'sample-1',
    title: '서울 문화 당일치기',
    travelDate: '2026-08-10',
    duration: 'day',
    places: [MOCK_PLACES[0], MOCK_PLACES[1], MOCK_PLACES[7]],
    totalVoucherAmount: 7000,
    totalSelfPay: 0,
    remainingBalance: 63000,
    createdAt: '2026-07-25',
  },
];
